language: java
jdk: openjdk6
script: mvn clean package
after_success: ./after_success.sh
env:
  global:
    - secure: wETu7SWmkKXQQI+pe5ypNG+SpJehCWy3pyaQInX30Wndvf+I+c3DOlPvvCB4Xu8m7L+R8x/jfxPFZv4H+JRBkyMKPGdm/9ooVFUfzZ+OZG3ajFyBQPnWy+9+QxqWxuvvKI1OTcgg+Lh1LX8c2vkViEr/qpIQXHEqCj8z0WC9yaM=
    - GH_USER_NAME: analytically
    - GH_PROJECT_NAME: innerbuilder
    - GIT_AUTHOR_NAME: "TravisCI"
    - GIT_AUTHOR_EMAIL: "noreply@travis-ci.org"
    - CI_HOME=`pwd`/$TRAVIS_REPO_SLUG